version: '3.8'

services:
  bot:
    build: .
    environment:
      ES_HOST: ${ES_HOST}
      ES_USERNAME: ${ES_USERNAME}
      ES_PASSWORD: ${ES_PASSWORD}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DEFAULT_ADMIN: ${DEFAULT_ADMIN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./RANCZO-WIDEO:/app/bot/RANCZO-WIDEO
      - ./RANCZO-TRANSKRYPCJE:/app/bot/RANCZO-TRANSKRYPCJE
