version: '3.8'

services:
  bot:
    build: .
    environment:
      ES_HOST: ${ES_HOST}
      ES_USER: ${ES_USER}
      ES_PASS: ${ES_PASS}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DEFAULT_ADMIN: ${DEFAULT_ADMIN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./bot/RANCZO-WIDEO:/app/bot/RANCZO-WIDEO
      - ./bot/RANCZO-TRANSKRYPCJE:/app/bot/RANCZO-TRANSKRYPCJE
